### ISSUE TITLE
Reduce dist build size

### ISSUE THREAD

**Issue by zachferland** [uport-project/3box-js#100]
Current dist file is a massive 9.4 mb, for comparison uport-connect is 0.7 mb (un minified 1.9) 

Should probably switch to webpack ( or rollup), features there will help reduce as well as control over other options

Also output both and minified and non minified version in the dist

**Comment by oed** [comment]
💯

**Comment by tzapu** [comment]
hey guys, current size is still kind of huge at 4.3MB, can anything more be done with it?
