### ISSUE TITLE
Direct muport-core to pinning server ipfs api

### ISSUE THREAD

**Issue by oed** [uport-project/3box-js#101]
Right now muport-core uses infura by default. Instead we should pass the configuration to reach the pinning-servers ipfs node in the opts to muport. This will pin the muport identity on the pinning-server rather than infura

**Comment by oed** [comment]
We should add the type `'PIN-DB'` to the pubsub publish message: https://github.com/uport-project/3box-pinning-server#request-to-pin

**Comment by oed** [comment]
@zachferland I'm not sure that the pinning server has opened the ports for this functionality yet (for this story and it's other on the address-server). 
@c-castillo Can you confirm that both port 5001 and 80 is open from the ipfs node on the pinning-server?

**Comment by c-castillo** [comment]
@oed @zachferland Ports 5001, 80, 443 are open on the pinning server.

**Comment by oed** [comment]
@c-castillo perfekt 👌
