### ISSUE TITLE
Developer builds

### ISSUE THREAD

**Issue by ozlemulusoy** [uport-project/3box-js#107]
Make sure end developers can include our lib easily in there build. It appears some of the build issues may be for other libs we depend on. In that case we have little control over that, but we should provide a solution to resolve it somewhere.

**Comment by oed** [comment]
Bumping the priority for this!

**Comment by zachferland** [comment]
May resolve some issues - https://github.com/uport-project/3box-js/pull/132, but still have to test, there may still be some other issues as well, so ongoing, until widely reliable

**Comment by zachferland** [comment]
https://github.com/uport-project/3box-js/issues/107 may also solve some issues

**Comment by zachferland** [comment]
https://github.com/uport-project/3box-js/issues/134

**Comment by zachferland** [comment]
https://github.com/uport-project/3box-js/issues/122 Resolved for now.

**Comment by zachferland** [comment]
Closing this issue now, all known issues where followed up with solutions and build improvement PRs merged in. New issues that come up, can be added as new issues.
