### ISSUE TITLE
Can't resolve 'child_process' when installing 3Box Library

### ISSUE THREAD

**Issue by KamesCG** [uport-project/3box-js#122]
**Describe the bug**
When installing the 3box module it appears the `child_process` dependency isn't being installed.

```
./node_modules/xmlhttprequest/lib/XMLHttpRequest.js
Module not found: Can't resolve 'child_process' in '/Users/admin/Documents/projects/unity/code/id-login/node_modules/xmlhttprequest/lib'
```

**To Reproduce**
1. npm install 3box@next
2. import ThreeBox from '3box'

**Expected behavior**
Initialize 3Box library.

**Screenshots**
![Dependency Issue](https://gateway.ipfs.io/ipfs/QmbK5XFHoe874F7BcSU7rESSFyKuEXQwKiB3KK1Z5xw25y)

**Comment by KamesCG** [comment]
After excluding `child_process` from the Webpack configuration file to avoid the I now get a `store` dependency issue.

Reference for excluding the `child_process` module: https://github.com/johnnynotsolucky/samples/commit/ab6f33ebd83ee00f84ebe64f6e8933a70fb9ab50

```
node: {
  child_process: 'empty',
  ...
}
```

![Store Dependencies](https://gateway.ipfs.io/ipfs/Qma7kqUARjEzgo2H5WpFE8CVRd18Yxwe3qdj6KURikuAer)

**Comment by KamesCG** [comment]
I found the issue with the `store` path as it was related to my project specifically.

In my Webpack configuration I had an alias that reconfigured the `store` path, so I renamed the alias and now everything is working as expected.

```
alias: {
  store:  path.resolve(__dirname, '../node_modules/store/dist/store.everything.js'),
  stores: path.resolve(__dirname, '../src/interface/store'),
  ....
```

**Comment by oed** [comment]
Ty @KamesCG. XMLHttpRequest is a node package that isn't required when in the browser. Not sure why it's causing an issue for you 🤔

**Comment by zachferland** [comment]
hey @KamesCG if you have a chance try with latest version, while not having `  child_process: 'empty'` in your build, interested if it works for others, we added a line in the package.json to hint to bundlers building our lib to exclude that module.

**Comment by rej156** [comment]
Might wanna update to Babel 7 too as you're already on webpack 4, may as well go the full way!

**Comment by zachferland** [comment]
@rej156 thanks for the tip! revisited it again and was able to upgrade to babel 7 in this pr https://github.com/uport-project/3box-js/pull/147

**Comment by zachferland** [comment]
Closing this issue, took multiple steps to minimize the problem, can re open if the issue continues to appear.

**Comment by tibetsprague** [comment]
I ran into this issue, which was resolved by adding
`  node: {
    fs: 'empty',
    child_process: 'empty'
  },
`
to my web pack config. I think you should add these instructions to the README
