### ISSUE TITLE
regeneratorRuntime is not defined [Beta 9]

### ISSUE THREAD

**Issue by GrandSchtroumpf** [uport-project/3box-js#125]
**Describe the bug**
When importing Threebox in my angular app I got : "regeneratorRuntime is not defined".

**To Reproduce**
- Clone this project : https://github.com/GrandSchtroumpf/ng-3box 
- Install dependancies : `npm install`
- Serve the app : `ng serve`

**Desktop (please complete the following information):**
 - OS: [Window]
 - Browser [Firefox and Chrome]
 - Version [latest]

**Additional context**
Worked with beta 7.

**Comment by oed** [comment]
@zachferland does this have something to do with some babel plugin missing?

**Comment by zachferland** [comment]
@oed yeah basically, for async/await functions, @GrandSchtroumpf we recently changed the build process, this seems to be a side effect of this, I'll have a fix soon, basically what joel said, need another babel plugin

**Comment by zachferland** [comment]
https://github.com/uport-project/3box-js/pull/128
