### ISSUE TITLE
openBox() should resolve after consent

### ISSUE THREAD

**Issue by GrandSchtroumpf** [uport-project/3box-js#126]
I think `openBox()` should resolve only after consent. Waiting for a consent is typically an async function that `Promise` should handle.
This is very confusing to have a callback in an option, and it makes it even more confusing that the callback doesn't act like the returned `Promise` ...

**Comment by oed** [comment]
The `openBox()` method returns a promise which resolves a `box` object. This is the purpose of this function. There is an optional parameter called `opts.consentCallback` which takes a function that will be called when the user gives consent. This is just needed if you want to change something in your app while this happens, but it's not really required.

**Comment by oed** [comment]
Closing this for now. Please reopen if anything is unclear.
