### ISSUE TITLE
Initial review of current master branch

### ISSUE THREAD

**Issue by christianlundkvist** [uport-project/3box-js#15]
Looked at the current master branch and I have a few initial questions:

# 3box.js file

1. There is a `getProfile` function to get the profile, but no corresponding `getPrivateData` for getting the private data. Do we want this or is this accessed directly through the `privateStore` member?

2. `getActivity` will be removed I assume?

3. Line 78 (`entropy = openBoxConsent(...)` - it seems we are grabbing entropy directly from a JSON string containing the signature? It’s unclear what the `openBoxConsent` function actually returns, aren’t there also a bunch of JSON metadata in there that is deterministic? I would suggest hashing the whole output from `openBoxConsent` and using that as entropy. Or returning known good entropy from `openBoxConsent`.

# profileStore.js

This file will need to use `ipfs.object.put` eventually instead of `ipfs.add`?

# utils.js

In `openBoxConsent`, we might want to drop the reference to `my.3box.io`. If we decide to change this URL in the future people would be signing a message containing a dead link.

**Comment by ajunge** [comment]
About your questions:

# 3box.js file

>1. There is a `getProfile` function to get the profile, but no corresponding `getPrivateData` for getting the private data. Do we want this or is this accessed directly through the `privateStore` member?

Probably we need that. But `getProfile` gets the whole json of the profile, while the privateData is queried key by key

>2. `getActivity` will be removed I assume?
Yes

>3. Line 78 (`entropy = openBoxConsent(...)` - it seems we are grabbing entropy directly from a JSON string containing the signature? It’s unclear what the `openBoxConsent` function actually returns, aren’t there also a bunch of JSON metadata in there that is deterministic? I would suggest hashing the whole output from `openBoxConsent` and using that as entropy. Or returning known good entropy from `openBoxConsent`.
@oed any comments on this?

# profileStore.js

>This file will need to use `ipfs.object.put` eventually instead of `ipfs.add`?
ipfs.add is an alias of ipfs.files.add 

# utils.js

>In `openBoxConsent`, we might want to drop the reference to `my.3box.io`. If we decide to change this URL in the future people would be signing a message containing a dead link.

Makes sense. But there is no way AFAIK to show non signing data on the signing window in Metamask

**Comment by oed** [comment]
> # 3box.js file
>>1. There is a `getProfile` function to get the profile, but no corresponding `getPrivateData` for getting the private data. Do we want this or is this accessed directly through the `privateStore` member?

>Probably we need that. But `getProfile` gets the whole json of the profile, while the privateData is queried key by key

The reason we have `getProfile` is because we need a way of getting the entire profile for someone else address. Note that this is a static function (i.e. you don't need to call openBox to call it). `getPrivateData` makes less sense to me. We should encourage devs to use the key to get specific entries. Also the keys are not explicitly saved anywhere (we only store `h(salt | key)` so we wouldn't be able to construct a useful JSON doc unless we change the implementation.


>3. Line 78 (`entropy = openBoxConsent(...)` - it seems we are grabbing entropy directly from a JSON string containing the signature? It’s unclear what the `openBoxConsent` function actually returns, aren’t there also a bunch of JSON metadata in there that is deterministic? I would suggest hashing the whole output from `openBoxConsent` and using that as entropy. Or returning known good entropy from `openBoxConsent`.

In the `openBoxConsent` we return [result.result](https://github.com/uport-project/3box-js/blob/master/src/utils.js#L21) IIRC this is the raw signature as a string. The bip39 lib takes a hex string and [generates a mnemonic](https://www.npmjs.com/package/bip39).

># profileStore.js
>>This file will need to use `ipfs.object.put` eventually instead of `ipfs.add`?

>`ipfs.add` is an alias of `ipfs.files.add`

@ajunge this is related to the IPLD story
@christianlundkvist We have a story for addressing this here: #2 

># utils.js
>In `openBoxConsent`, we might want to drop the reference to `my.3box.io`. If we decide to change this URL in the future people would be signing a message containing a dead link.

This is quite the tradeoff.
cc @michaelsena

**Comment by christianlundkvist** [comment]
> In the openBoxConsent we return result.result IIRC this is the raw signature as a string. The bip39 lib takes a hex string and generates a mnemonic.

Ok this is good, but I’d rather hash the return value rather than truncating it, in order to make sure that all the entropy from the signature is accounted for.

> getPrivateData

I guess my question is more about if we want the 3Box.js interface to be complete. I.e if I understand it correctly we would now instead get a “privateStore” object from the 3Box object and then need to look at the interface for privateStore in order to know how to use it, instead of getting/setting private data directly from the 3Box object.

> getprofile is static

Hmm this might be an issue if we move to a more flexible model than assuming that the mapping from address to hash is provided by the 3Box server. 🤔

**Comment by oed** [comment]
> openBoxConsent

Ah, ok. That makes sense. I'll create a story for that.

> getPrivateData

Yes, I think this is the right approach. The alternative would be to have methods such as `getPrivate` and `getPublic` which is more confusing imo. Especially if we are considering adding name spaced stores in the future. 

> getProfile is static

How so? I don't think there is much use with public profiles if you can only read your own profile.

**Comment by michaelsena** [comment]
Thanks, @oed circling back on this to repeat what we mentioned on the call. I'm cool dropping the 3box.io URL from the consent message because I don't expect we acquire many dapp users that way during the launch. I think it will be social influencer marketing that drives users to 3box.io to create an Ethereum profile.

**Comment by christianlundkvist** [comment]
All relevant action items have been converted into concrete issues. Closing this one.
