### ISSUE TITLE
Only sync local data to remote upon (closing and reopening store) 

### ISSUE THREAD

**Issue by zachferland** [uport-project/3box-js#152]
**Describe the bug**
Run in dapp1, and run in dapp2, open box in dapp1, and add key/value. Then go to dapp2 and open box, new key is not available. 

But if you then close dapp1, and reopen box in dapp1. Then go to dapp2, now the new key/value will be available. Must only be syncing on opening. 

**Expected behavior**
Open box in dapp1, add new key/value. Open box in dapp2, see new key/val there as well. 

**Desktop (please complete the following information):**
 - Version 1.0.0 3box-js

**Comment by oed** [comment]
hm, I thought this would be solved by `onSyncDone`

**Comment by zachferland** [comment]
For what ever reason, I think the remote is only get the most recent local data on opening, not on write.  Not really related to onSyncDone, I don't think

**Comment by zachferland** [comment]
for example reinit everything in dapp2, it will sync from remote and call onSyncDone, but it won't get new key/val from dapp1, until that is reopened

**Comment by oed** [comment]
Strange, sounds like a bug in the pinning-server or in orbit-db

**Comment by zachferland** [comment]
Might have been temporary (corrupted local orbitdb/ipfs local state or something), going to close. Will reopen if it can be recreated again.
