### ISSUE TITLE
Add Access Control Section to Documentation

### ISSUE THREAD

**Issue by michaelsena** [uport-project/3box-js#17]

**Comment by christianlundkvist** [comment]
Added an Access Control section to the Wiki here:

https://github.com/uport-project/3box/wiki/1a.-3Box-Architecture

**Comment by christianlundkvist** [comment]
Can you take a look at the above @oed @michaelsena?

**Comment by oed** [comment]
@christianlundkvist looks good. I think this should live in the ARCHITECTURE.md document though.

**Comment by oed** [comment]
@michaelsena @christianlundkvist Do you think the Wiki is useful? To me it seems just like a place where we duplicate the documentation that is in the repo anyway + it's harder to find.

**Comment by christianlundkvist** [comment]
@oed Yeah it might be better to just write that paragraph in ARCHITECTURE.md to begin with. Not sure if the wiki really helps. I think it might be better to have a "table of contents" in README.md that points to the individual documents. That way people have a good entry point and we're not duplicating documentation.

**Comment by michaelsena** [comment]
Agreed @oed and @christianlundkvist. I’ll remove the wiki this sprint.

**Comment by christianlundkvist** [comment]
@michaelsena @oed Updated in the ARCHITECTURE.md in this PR:

https://github.com/uport-project/3box/pull/192
