### ISSUE TITLE
Option to add infura key

### ISSUE THREAD

**Issue by ChrisCates** [uport-project/3box-js#184]
Referencing `ipfs-mini` issue here: https://github.com/SilentCicero/ipfs-mini/issues/10, since there is no option to provide a query string for IPFS storage for 3box right now.

Would be nice to iterate an update afterwards with an option to pass query string into the constructor... Since Infura requires a key to access storage (from my knowledge at least).

**Comment by oed** [comment]
Thanks for reporting @ChrisCates! We are actually looking to move away from infura ourselves, and instead use our own ipfs node. You can follow the progress in these PRs:
https://github.com/uport-project/3box-pinning-server/pull/17
https://github.com/uport-project/3box-address-server/pull/36
https://github.com/uport-project/3box-js/pull/146


Hope that answers your question!

**Comment by ChrisCates** [comment]
Great, thanks for the update!
