### ISSUE TITLE
Use .del(key) to delete entries from privateStore

### ISSUE THREAD

**Issue by oed** [uport-project/3box-js#23]
We are using `set(key, null)` to remove values from the orbitdb kv-store in the private store. As it turns out there is a function `.del(key)` which we should be using.

```
oed
Yo, is there a convention to remove a KV-pair from the keyvalue store? 
Right now I'm doing db.set('mykey', null)

Haad (Gitter)
@oed db.del('mykey')
...which I now realize is not documented in the API docs :O
```

cc @christianlundkvist

**Comment by christianlundkvist** [comment]
PR is here: https://github.com/uport-project/3box-js/pull/33

**Comment by christianlundkvist** [comment]
This has been merged, so closing this issue.
