### ISSUE TITLE
No padding in private store encryption

### ISSUE THREAD

**Issue by oed** [uport-project/3box-js#38]
Right now there is no padding in the encyption as specified in the [architecture spec](https://github.com/uport-project/3box/blob/master/ARCHITECTURE.md#encryption)

**Comment by michaelsena** [comment]
Hey zach, this was moved 5 days ago. Any update here?

**Comment by zachferland** [comment]
had almost started it before having to return to some remaining uport lib work, still will pick up within day or two

**Comment by michaelsena** [comment]
@zachferland can you please move this story back to ready to start and then move it back to in progress when you actually begin the work? It's helpful if stories accurately represent work, so we have an understanding of what's going on

**Comment by zachferland** [comment]
👍
