### ISSUE TITLE
Add timestamps to DB updates/events

### ISSUE THREAD

**Issue by michaelsena** [uport-project/3box-js#44]

**Comment by zachferland** [comment]
@oed @michaelsena what is considered events here? you mean updates? and in that case do we intend to keep an 'event' history? since at the moment the state is the set of most recent writes to any given key?

**Comment by zachferland** [comment]
Chatted with @oed and we resolved. Events at the underlying log level, not user level concept of events. Yes we only keep the current stores available, but having the history is nice, which is available in the underlying log of the store. This is issue https://github.com/uport-project/3box-js/issues/50 is to create an api at the 3box level making this concept/data available. These timestamps are friendly for an end user and the UI. The underlying log is time ordered with a lamport clock, while our timestamps are useful for UI time ordering. While there is few replications and events at this time, these two orderings should be equivalent for now, but it may not hold in the future.
