### ISSUE TITLE
public and private are restricted keywords in 'strict mode' js

### ISSUE THREAD

**Issue by oed** [uport-project/3box-js#69]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#Paving_the_way_for_future_ECMAScript_versions

This means that we shouldn't use `box.public` and `box.private` which sucks because they where really good names. 

Anyone have any suggestions of what we could use instead?

cc @michaelsena @zachferland @christianlundkvist

**Comment by michaelsena** [comment]
Ah, didn’t know this either. So are we not allowed to use the words at all, or just not as standalone words? For example could we do something like box.pub.set and box.priv.set or box.publicdata.set?

**Comment by zachferland** [comment]
hah ah did not think of that, let me see if I got any other suggestions 
yeah priv/pub is possible, but yeah don't like it as much

**Comment by zachferland** [comment]
do we expect to have a bunch of boxes in the future? if so should pick naming friendly to that. Or will that be abstracted, such that they are just subspaces in the public and private stores

**Comment by oed** [comment]
@zachferland I don't think we know that yet. But technically we'll have more orbitdb stores that the dev will have to request access to. How the api will look like is still unclear.

**Comment by oed** [comment]
Don't see any major reason to address this.
