### ISSUE TITLE
Don't use fs and child_process (in xmlhttprequest)

### ISSUE THREAD

**Issue by GrandSchtroumpf** [uport-project/3box-js#81]
**Describe the bug**
`3box-js` uses `fs`and `child_process` that are two node modules that cannot be browserified.
Angular prevents any app to use libraries that make calls to `fs` or `child_process`.
Here are the error messages : 
```
ERROR in ./node_modules/xmlhttprequest/lib/XMLHttpRequest.js
Module not found: Error: Can't resolve 'child_process' in ''$YOUR_PROJECT\node_modules\xmlhttprequest\lib'
ERROR in ./node_modules/xmlhttprequest/lib/XMLHttpRequest.js
Module not found: Error: Can't resolve 'fs' in '$YOUR_PROJECT\node_modules\xmlhttprequest\lib'
```

**To Reproduce**

1. install @angular/cli : `npm install -g @angular/cli`
2. create a new project in a folder : `ng new ng-3box`
3. cd into this project : `cd ng-3box`
4. install 3box : `npm install 3box@next --save`
5. Serve the app : `ng serve`

**Expected behavior**
3Box shouldn't use modules that have no browserified version such as `fs`or `child_process`.
Use that browser native xmlhttprequest instead of the node version.

**Desktop (please complete the following information):**

 - OS: [Windows 10]
 - Browser [Firefox]
 - Version [latest]

**Comment by oed** [comment]
Hey, thanks for reporting! 

I have not encountered this problem when browserifying the 3box lib. Currently we use `XMLHttpRequest` in `src/utils.js` with the following code:
```js
const XMLHttpRequest = (typeof window !== 'undefined') ? window.XMLHttpRequest : require('xmlhttprequest').XMLHttpRequest
```
That should use the browsernative one when browserifying. If you need an already browserified version of the library you can use `dist/3box.js`

**Comment by GrandSchtroumpf** [comment]
Ok thx, I managed to work around.

**Comment by oed** [comment]
Glad that you got it working 😊

**Comment by GrandSchtroumpf** [comment]
@oed I wrote an article to explain how to build a `3box-js` project with angular : 
https://medium.com/@GrandSchtroumpf/3box-and-angular-6-994cbde60aa9 
And the associated github repo : 
https://github.com/GrandSchtroumpf/ng-3box 

I hope it can be useful.

**Comment by michaelsena** [comment]
@GrandSchtroumpf this is so awesome! Thank you for jumping into the code with us this early in the process. We're obviously working out some of the final kinks, but I hope you're finding the project useful! Feel free to hang around and lmk if you have any questions 👍

**Comment by oed** [comment]
@GrandSchtroumpf that's really cool! I second everything @michaelsena said, also please let us know any pain points that you've had or experience in the future 🙂
