### ISSUE TITLE
Several data store depending on the dapp

### ISSUE THREAD

**Issue by GrandSchtroumpf** [uport-project/3box-js#87]
Hi, 
Is it possible to have different data store for the same address, depending on the dapp I am on? 
Sorry to put that in the issues, I would normally go to Stackoverflow, but as it is an early stage project, I thought it would make more sense here.

**Comment by oed** [comment]
Not yet, we want to gather more feedback on our initial release. Thanks for raising though, now we know that there is demand for it :)
