### ISSUE TITLE
Wrong doc

### ISSUE THREAD

**Issue by GrandSchtroumpf** [uport-project/3box-js#90]
The documentation for method `getProfile` says only `opts.ipfs` to describe the options.
In `src/3box.js` there are 3 keys checked : 
- opts.ipfsOptions
- opts.addressServer
- opts.orbitPath

**Comment by oed** [comment]
You're right, thanks for reporting!

**Comment by christianlundkvist** [comment]
Fixed in the following PR: 

https://github.com/uport-project/3box-js/pull/124

**Comment by christianlundkvist** [comment]
PR is merged, closing.
