### ISSUE TITLE
Stop waiting for replication from network if no data on pinning-server

### ISSUE THREAD

**Issue by oed** [uport-project/3box-js#94]
openBox currently waits for replication from pinning server if the odb-address is present. This causes #93. 

Pinning server is implementing pubsub responses https://github.com/uport-project/3box-pinning-server/issues/2 one of which is to respond that it has no data for a particular event. If this response is received we should create a new rootStore instead of wait for it to be replicated.

**Comment by oed** [comment]
@cri

**Comment by c-castillo** [comment]
No, why did you close it?

**Comment by oed** [comment]
Oh, that must have been an error. Just open it again!

**Comment by oed** [comment]
Closing this in favor of #142
